CREATE TABLE "Character" (
    "id" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "birthDate" TEXT,
    "century" INTEGER NOT NULL,
    "campaign" TEXT,
    "playerName" TEXT,
    "concept" TEXT NOT NULL,
    "ancestry" TEXT NOT NULL,
    "ancestryCustom" BOOLEAN NOT NULL DEFAULT false,
    "path" TEXT NOT NULL,
    "pathCustom" BOOLEAN NOT NULL DEFAULT false,
    "bond" TEXT NOT NULL,
    "bondCustom" BOOLEAN NOT NULL DEFAULT false,
    "oathOrDebt" TEXT,
    "mark" TEXT NOT NULL DEFAULT 'keins',
    "attributes" JSONB NOT NULL,
    "skills" JSONB NOT NULL,
    "equipment" JSONB NOT NULL,
    "supernatural" JSONB NOT NULL,
    "conditions" JSONB NOT NULL,
    "notes" TEXT,
    "woundThreshold" INTEGER NOT NULL,
    "burdenThreshold" INTEGER NOT NULL,
    "initiative" INTEGER NOT NULL,
    "faithLevel" INTEGER NOT NULL,
    "magicLevel" INTEGER NOT NULL,
    "omenMax" INTEGER NOT NULL,
    "invocationValue" INTEGER NOT NULL,
    "favorLimit" INTEGER NOT NULL,
    "arkanaMax" INTEGER NOT NULL,
    "favorMax" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Character_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Character_hash_key" ON "Character"("hash");
